package opcode

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"strconv"
)

var NotLogCP map[uint8]bool = map[uint8]bool{
	CP_AliveAck: true,
	CP_UserMove: true,
	CP_MobMove:  true,
	CP_NpcMove:  true,
}

var NotLogLP map[uint8]bool = map[uint8]bool{
	LP_AliveReq: true,
	LP_UserMove: true,
	// LP_MobMove:  true,
	// LP_NpcMove:  true,
}

// Format opcodes for Debugging
func GenOpcodeMap(originPath, targetPath, mapName string) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, originPath, nil, parser.AllErrors)
	if err != nil {
		panic(err)
	}
	out, err := os.Create(targetPath)
	if err != nil {
		panic(err)
	}
	defer out.Close()
	fmt.Fprintln(out, "// Code generated by opcode_test, DO NOT EDIT.")
	fmt.Fprintln(out, "package opcode")
	fmt.Fprintf(out, "\nvar %s map[uint8]string = map[uint8]string{", mapName)
	fmt.Fprintln(out, "")
	ast.Inspect(f, func(n ast.Node) bool {
		switch v := n.(type) {
		case *ast.ValueSpec:
			for i, name := range v.Names {
				if i >= len(v.Values) {
					continue
				}
				basicLit, ok := v.Values[i].(*ast.BasicLit)
				if !ok {
					continue
				}
				value, err := strconv.ParseInt(basicLit.Value, 0, 16)
				if err != nil {
					continue
				}
				if value > 255 {
					continue
				}
				fmt.Fprintf(out, "\t0x%X: \"%s\",\n", value, name.Name)
			}
		}
		return true
	})
	fmt.Fprintln(out, "}")
}
